### ISSUE TITLE
Support for GHC 8.10

### ISSUE THREAD

**Issue by sjakobi** [snapframework/io-streams-haproxy#19]
AFAICT only the bound on `base` needs to be bumped.

**Comment by mightybyte** [comment]
Done

**Comment by sjakobi** [comment]
Thanks! If you could do the same for [`snap-server`](https://github.com/snapframework/snap-server/issues/128), that would be great! :)

**Comment by mightybyte** [comment]
Build isn't passing yet for some reason.  :/
