### ISSUE TITLE
getPeerName: invalid argument (Transport endpoint is not connected)

### ISSUE THREAD

**Issue by hvr** [snapframework/io-streams-haproxy#2]
I'm using code like the following, which causes problems with `haproxy`s default keepalive check which consists in sending a `PROXY` header and closing the connection right ahead:

```haskell
(s,sa) <- accept sock
(inst,outst) <- socketToStreams s
localPInfo <- socketToProxyInfo s
```

The problem is that by the time `getPeerName` is called, the connection is already closed, so the system calls fails.

However, if I there was a function which allowed me to pass in the `sa` I already got from the `accept`, i.e.

```haskell
socketToProxyInfo :: N.Socket -> IO ProxyInfo
socketToProxyInfo s = socketToProxyInfoWithPeerName s =<< N.getPeerName s

socketToProxyInfoWithPeerName :: N.Socket -> N.SockAddr -> IO ProxyInfo
socketToProxyInfoWithPeerName s sa = do
    da <- N.getSocketName s
    let (N.MkSocket _ _ !sty _ _) = s
    return $! makeProxyInfo sa da (addrFamily sa) sty
```

I can write the code like below and avoid calling `getPeerName` (and thus avoid the failure):

```haskell
(s,sa) <- accept sock
(inst,outst) <- socketToStreams s
localPInfo <- socketToProxyInfoWithPeerName s sa
```

**Comment by gregorycollins** [comment]
OK, I'm about to fix this, but I'll have to ask you to test it. I'm worried the call to `getSocketName` is going to cause the same issue.
