### ISSUE TITLE
Compatibility with GHC 9.2

### ISSUE THREAD

**Issue by sjakobi** [snapframework/io-streams-haproxy#25]
As far as I can tell, `io-streams-haproxy-1.0.1.0` is already buildable with GHC-9.2 when the upper bounds on `base` and `bytestring` are relaxed. Could you adjust these bounds?

**Comment by cydparser** [comment]
This issue can be closed after PR #26 is merged.

**Comment by ysangkok** [comment]
This can be closed now as @cydparser mentions.
